%YAML:1.0

# 1: realtime, 0: non-realtime
test.RealTime: 0
# Time for visual-inertial initialization
test.VINSInitTime: 15.0

# Modify test.InitVIOTmpPath and bagfile to the correct path
# Path to save tmp files/results
test.InitVIOTmpPath: "/opt"

## For good initialization (no movement at the beginning for some bag)
test.DiscardTime: 0
#test.DiscardTime: 18

bagfile: "/opt/mynteye_atrium_dolphin.bag"

#######################################

imutopic: "/mynteye/imu/data_raw"
imagetopic: "/mynteye/left/image_raw"


# Timestamp shift. Timage = Timu + image_delay
Camera.delaytoimu: 0

# acc=acc*9.8, if below is 1
IMU.multiplyG: 0

# camera-imu frame transformation, Pi = Tic * Pc
Camera.Tbc:
 [-0.016250607827436148, -0.9998512405245886, -0.005780533425264023, -0.07513204265405812,
  -0.0024240900898974127, 0.005820677335537122, -0.9999801215537197, 0.003491915705214365,
  0.9998650116553109, -0.016236272256810902, -0.002518319028197158, -0.0349640569908768,
  0.0, 0.0, 0.0, 1.0]

# Local Window size
LocalMapping.LocalWindowSize: 20

#--------------------------------------------------------------------------------------------
# Camera Parameters. Adjust them!
#--------------------------------------------------------------------------------------------

# Camera calibration and distortion parameters (OpenCV) 
Camera.fx: 366.464829202444 
Camera.fy: 366.6496267746324
Camera.cx: 371.10794906761015
Camera.cy: 243.15915597651244

Camera.k1: -0.3186453409161979
Camera.k2: 0.09961770731315886
Camera.p1: 0.0004079858543647025
Camera.p2: 9.082890892238505e-05

# Camera frames per second 
Camera.fps: 30.0

# IR projector baseline times fx (aprox.)
Camera.bf: 40.0

# Color order of the images (0: BGR, 1: RGB. It is ignored if images are grayscale)
Camera.RGB: 1

# Close/Far threshold. Baseline times.
ThDepth: 40 

# Deptmap values factor
DepthMapFactor: 1.0

#--------------------------------------------------------------------------------------------
# ORB Parameters
#--------------------------------------------------------------------------------------------

# ORB Extractor: Number of features per image
ORBextractor.nFeatures: 1000

# ORB Extractor: Scale factor between levels in the scale pyramid 
ORBextractor.scaleFactor: 1.2

# ORB Extractor: Number of levels in the scale pyramid 
ORBextractor.nLevels: 8

# ORB Extractor: Fast threshold
# Image is divided in a grid. At each cell FAST are extracted imposing a minimum response.
# Firstly we impose iniThFAST. If no corners are detected we impose a lower value minThFAST
# You can lower these values if your images have low contrast   
ORBextractor.iniThFAST: 20
ORBextractor.minThFAST: 7

#--------------------------------------------------------------------------------------------
# Viewer Parameters
#--------------------------------------------------------------------------------------------
Viewer.KeyFrameSize: 0.05
Viewer.KeyFrameLineWidth: 1
Viewer.GraphLineWidth: 0.9
Viewer.PointSize:2
Viewer.CameraSize: 0.08
Viewer.CameraLineWidth: 3
Viewer.ViewpointX: 0
Viewer.ViewpointY: -0.7
Viewer.ViewpointZ: -1.8
Viewer.ViewpointF: 500

